### ISSUE TITLE
docs: 更新可用winget下载的版本

### ISSUE THREAD

**Issue by DuckDuckStudio** [DuckDuckStudio/Fufu_Tools#104]
### 在继续之前，请确认以下内容

- [X] 我已经搜索过已存在的问题，并没有存在相同的正在进行中/重复/已解决的问题
- [X] 如果该问题在预览版中被解决，我没有被告知

### 选择一个问题类别

winget相关问题

### 描述你遇到的问题

- microsoft/winget-pkgs#167397
~~一直都是 [Binary-Validation-Error](https://github.com/microsoft/winget-pkgs/labels/Binary-Validation-Error)~~

### 描述如何重现你遇到的问题

/

### 实际行为

/

### 预期行为

通过检查并可通过winget安装

### 确认相关信息

```raw
No merge.
```

**Comment by DuckDuckStudio** [comment]
自动验证通过，应该可以了

**Comment by Luna-Grace** [comment]
今晚似乎没有审查...还得等几天，要改文档吗？

**Comment by DuckDuckStudio** [comment]
> 要改文档吗？

要的
