### ISSUE TITLE
[Feat]: 为自动打包工具添加开始打包时的输出

### ISSUE THREAD

**Issue by DuckDuckStudio** [DuckDuckStudio/Fufu_Tools#109]
### 对新功能/建议的描述

如题

### 为什么需要实现此功能 (可选)

如果不添加，很容易将上个成功消息看成这次打包的文件，并且如果整个炸了就看不到到底是哪个文件炸。

### 对于实施该功能的方法的建议 (可选)

如题

**Comment by Luna-Grace** [comment]
这样要如何区分开始与结束的输出呢？中间加点`-`？加多少？
