### ISSUE TITLE
[BUG]: 日志中不应出现颜色

### ISSUE THREAD

**Issue by Luna-Grace** [DuckDuckStudio/Fufu_Tools#113]
### 在继续之前，请确认以下内容

- [X] 我已经搜索过已存在的问题，并没有存在相同的正在进行中/重复/已解决的问题
- [X] 如果该问题在预览版中被解决，我没有被告知

### 选择一个问题类别

使用问题

### 描述你遇到的问题

在自动打包py文件程序炸了时日志文件会被写入颜色

### 描述如何重现你遇到的问题

1. 使用工具打包任意py文件
2. 等打包出错
3. 查看日志

### 实际行为

/

### 预期行为

日志中没有颜色

### 确认相关信息

<details>
    <summary>相关信息</summary>
    <pre><code>
--- Console used encoding ---
Active code page: 65001
--- System version ---

Microsoft Windows [Version 10.0.22631.4169]
--- System Architecture ---
 x64
--- Fufu Tools version ---
--------------芙芙工具箱--------------
-> Code by 鸭鸭「カモ」/ DuckStudio
Version: v1.3.5-code
-------------------------------------
--- Installed library files ---
Package                   Version
------------------------- --------
altgraph                  0.17.4
beautifulsoup4            4.12.3
certifi                   2024.6.2
chardet                   5.2.0
charset-normalizer        3.3.2
click                     8.1.7
colorama                  0.4.6
configparser              7.0.0
decorator                 4.4.2
experimental              0.9.7
idna                      3.7
imageio                   2.34.1
imageio-ffmpeg            0.5.1
keyboard                  0.13.5
libretranslatepy          2.1.1
lxml                      5.2.2
MouseInfo                 0.1.3
moviepy                   1.0.3
ntplib                    0.4.0
Nuitka                    2.3
numpy                     1.26.4
ordered-set               4.1.0
packaging                 24.0
pefile                    2023.2.7
piexif                    1.1.3
pillow                    10.3.0
pip                       24.0
plyer                     2.1.0
proglog                   0.1.10
PyAutoGUI                 0.9.54
pygame                    2.5.2
PyGetWindow               0.0.9
pyinstaller               6.7.0
pyinstaller-hooks-contrib 2024.6
PyMsgBox                  1.0.9
pyperclip                 1.8.2
PyRect                    0.2.0
PyScreeze                 0.1.30
pytweening                1.2.0
pywin32                   306
pywin32-ctypes            0.2.2
requests                  2.32.3
setuptools                70.0.0
soupsieve                 2.5
tqdm                      4.66.4
translate                 3.6.1
urllib3                   2.2.1
zstandard                 0.22.0

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip
--- Directory where Fufu Tools is located ---
d:\...\Fufu_Tools
--- Network connection status ---
Connection normal
[INFO] Using IPv6.
Connection normal
[INFO] Using IPv4.
--- Github connection status ---
Connection normal
--- limits of authority ---
Non administrator.
--- System environment ---
Python 3.12.0
pip 24.0 from D:\...\Fufu_Tools\.venv\Lib\site-packages\pip (python 3.12)
    </code></pre>
</details>

### 屏幕截图或日志 (可选)

> For DEV: 已验证BUG、可稳定复现

**Comment by DuckDuckStudio** [comment]
竟然是我的BUG ━━━∑(ﾟ□ﾟ*川━
✕ 优化 | ✓ 全新BUG
![image](https://github.com/user-attachments/assets/15ed6712-7dd2-4bed-ab52-01ee31c03e54)
