### ISSUE TITLE
[BUG]: 自动打包py/pyw文件时日志文件路径最后必须带`/`

### ISSUE THREAD

**Issue by fjwxzde** [DuckDuckStudio/Fufu_Tools#123]
### 在继续之前，请确认以下内容

- [X] 我已经搜索过已存在的问题，并没有存在相同的正在进行中/重复/已解决的问题
- [X] 如果该问题在预览版中被解决，我没有被告知

### 选择一个问题类别

使用问题

### 描述你遇到的问题

See Line 165.

### 描述如何重现你遇到的问题

/

### 实际行为

/

### 预期行为

/

### 确认相关信息

```raw
In test repo.
```

**Comment by Luna-Grace** [comment]
Will be fixed at 1.3.5
