### ISSUE TITLE
[实验性小工具] 自动左键连点/自动按键连按 可能问题

### ISSUE THREAD

**Issue by WXZing** [DuckDuckStudio/Fufu_Tools#21]
在这两个工具的间隔时间输入错误值可能导致程序崩溃，如果可以，请**给出提示并让用户重新输入正确值**。
![3](https://github.com/DuckDuckStudio/Fufu_Tools/assets/106975825/4c0191bc-e2cc-4ef8-93d4-41e41c884f59)
(tag:bug,输出)

**Comment by DuckDuckStudio** [comment]
已在最新提交中修复，感谢支持
