### ISSUE TITLE
[实验性小工具] 自动按键连按 可能问题

### ISSUE THREAD

**Issue by WXZing** [DuckDuckStudio/Fufu_Tools#22]
在这个工具中如果输入需要连按的按键为 `xhaudhcaidh`等乱输或意外多输的按键时，程序可能会出现意外。
请不要将按键限定为字母，必须包含 `F1`、`ESC`等这样的按键。
如图所示，程序没有报错，但也没有执行连按。但在后续测试中，程序对于 `win`键可以连按（但必须输入 `win`,输入 `windows`则无效）
![4](https://github.com/DuckDuckStudio/Fufu_Tools/assets/106975825/47bcb136-b57c-49d3-9f8b-df8b484baafe)
一个可能的解决办法：列出 `pyautogui`库可以模拟按下的全部按键，如果输入不在列表内则将其排除。如果这样做，具体支持的按键列表必须同时给出。

(tag:bug)

**Comment by DuckDuckStudio** [comment]
已在最新提交中修复，将在v1.2.8及后续版本发布
