### ISSUE TITLE
[优化]初始化环境时使用虚拟环境/使用Nuitka打包

### ISSUE THREAD

**Issue by abyss-zues** [DuckDuckStudio/Fufu_Tools#26]
1.不建議使用zip格式壓縮
ZIP格式不記錄文件名編碼格式，你的電腦是簡體中文版的Windows默認使用GBK，然而不使用簡體中文版Windows電腦的解壓出來就是亂碼。
2.我不清楚是我電腦的問題還是啥問題，打開功能就報錯，顯示找不到文件
![image](https://github.com/DuckDuckStudio/Fufu_Tools/assets/110171545/0cb5eab9-6094-4035-b56a-f76732230fb7)
為什麼不直接import，然後調用呢
3.在初始化環境的時候，建議自動創建虛擬環境，直接在系統環境裡安裝庫確實不好。
4.可以嘗試使用Nuitka打包一下這個lite版本，這樣運行速度還能更快一點，還能更穩定一些

**Comment by DuckDuckStudio** [comment]
对于第2个问题，你提到编码不同，可能是由于编码问题导致文件夹/文件名名称不同进而导致找不到文件（仅为猜测）

**Comment by abyss-zues** [comment]
虚拟环境在使用时应该不用激活，我尝试一下能不能实现吧

**Comment by abyss-zues** [comment]
![image](https://github.com/DuckDuckStudio/Fufu_Tools/assets/110171545/67cea970-d3e2-45b7-8b85-5f80297b8f09)
可以在软件启动的时候检查是否有虚拟环境，如果有就把那两个变量改了

**Comment by abyss-zues** [comment]
然后在pip的时候调用改虚拟环境的pip.exe就行了

**Comment by DuckDuckStudio** [comment]
对于第4点，Nuitka似乎不支持Python3.12
```
FATAL: The Python version '3.12' is not supported by Nuitka '2.1.5', but an upcoming release will add it. In the mean time use '3.11' instead.
```

**Comment by DuckDuckStudio** [comment]
遇到了点问题：
[相关信息.zip](https://github.com/DuckDuckStudio/Fufu_Tools/files/14998593/default.zip)
```
scons: *** [D:\Duckhome\CODEDE~1\FUFU_T~1.8-N\BDE7~1.DIS\芙芙工具箱.exe] Error 1
FATAL: Failed unexpectedly in Scons C backend compilation.
Nuitka:WARNING:     Complex topic! More information can be found at
Nuitka:WARNING: https://nuitka.net/info/scons-backend-failure.html
Nuitka-Reports: Compilation crash report written to file 'nuitka-crash-report.xml'.
```

**Comment by abyss-zues** [comment]
1.standalone和onefile有点冲突，onefile本来就是standalone。
2.因为你的用户名是中文，然后Nuitka把编译器安装到了你的用户目录下，编译器应该不支持中文路径，你可以尝试换一下编译器路径，或者换编译器。

**Comment by DuckDuckStudio** [comment]
对于使用Nuitka打包，超出了我预计的时间，我只会将其用到一些其他项目上。
感谢您的建议，希望打开程序的问题也已在v1.2.8-1发布后不再发生。

**Comment by WXZing** [comment]
> 对于你提到的问题：
> 
> 1. 我已将编码统一为UTF-8（之前没想到会有不是简体中文的系统用），后续仍会使用zip格式压缩，因为这个压缩格式兼容性较好，且可以直接在Windows上解压。
> 2. 这个问题我无法重现，因为我目前只遇到已知问题Issues [[实验性小工具] [Warn]批量水印添加 在主程序中的路径错误 #19](https://github.com/DuckDuckStudio/Fufu_Tools/issues/19)，在pr [Fix Issues #19 & Maybe fix Issues #20 #23](https://github.com/DuckDuckStudio/Fufu_Tools/pull/23) 修复
> 3. 目前没有这个考虑，因为虚拟环境在重启后还需激活才可import（另：环境配置已经有一些优化，将在v1.2.8版本更新，[相关提交](https://github.com/DuckDuckStudio/Fufu_Tools/commit/4d1aba473a9bae0ab87d57862ea405b27eddb287)）
> 4. 对于打包，我目前使用的是pyinstaller + UPX（v1.2.7及以前未使用UPX），我将在v1.2.8版本尝试两者...（以防出现问题）
>    感谢您对本项目的支持！

你似乎忘了`#!/.venv/Scripts/python.exe`

**Comment by DuckDuckStudio** [comment]
已提交修改，待编写文档。

**Comment by DuckDuckStudio** [comment]
已编写文档

**Comment by DuckDuckStudio** [comment]
已在 [V1.3.1-1](https://github.com/DuckDuckStudio/Fufu_Tools/releases/tag/v1.3.1-1) 中发布优化后的虚拟环境配置程序
~~提前清下标签，反正半夜也没人知道我还没发~~
