### ISSUE TITLE
[文档,长期]有暂时缺失的文档可在此评论

### ISSUE THREAD

**Issue by DuckDuckStudio** [DuckDuckStudio/Fufu_Tools#45]
2024年5月27日 11:18
**开发工具文档**待更新

---

2024年5月27日 12:12
已更新 [docs:更新芙芙工具箱开发工具文档](https://github.com/DuckDuckStudio/yazicbs.github.io/commit/e9356a8461bd212bf5fa1e17ec8be35ec98d18a8)

**Comment by Luna-Grace** [comment]
> [!TIP]
> 如果有新需求，请指派所有者@DuckDuckStudio

**Comment by Luna-Grace** [comment]
> [!WARNING]
> 切勿将本issue移至已完成规划分类

**Comment by DuckDuckStudio** [comment]
Issue #59 已添加到`[实验性]`分类下，网站上的`[实验性]`工具文档待更新。

**Comment by DuckDuckStudio** [comment]
官网下载链接待更新

**Comment by DuckDuckStudio** [comment]
已更新文档

**Comment by CoolPlayLin** [comment]
@DuckDuckStudio https://github.com/microsoft/winget-pkgs/pull/160522#issuecomment-2211629220

**Comment by DuckDuckStudio** [comment]
> @Luna-Grace [microsoft/winget-pkgs#160522 (comment)](https://github.com/microsoft/winget-pkgs/pull/160522#issuecomment-2211629220)

microsoft/winget-pkgs#162308

**Comment by Luna-Grace** [comment]
网站未更新
