### ISSUE TITLE
软件大小能否优化一下，占用空间实在是大

### ISSUE THREAD

**Issue by lzsweibaoguo777** [DuckDuckStudio/Fufu_Tools#69]
软件大小能否优化一下，占用空间实在是大😂

**Comment by DuckDuckStudio** [comment]
`lite`版也大？

**Comment by DuckDuckStudio** [comment]
@fjwxzde set

**Comment by Luna-Grace** [comment]
@lzsweibaoguo777 使用的是哪个版本呢？**如果不是`lite`版请试着去使用`lite`版**，如果是，请说明您对优化后的大小的期望。

**Comment by fjwxzde** [comment]
@lzsweibaoguo777 如果7日内没有回复，此issue将视为解决并关闭。

**Comment by DuckDuckStudio** [comment]
由于长时间没有活动，此Issue视为解决并关闭。
如有需要可重新打开。
