### ISSUE TITLE
[新功能] 可以设置一个分类来与你编写的其他程序联动

### ISSUE THREAD

**Issue by Luna-Grace** [DuckDuckStudio/Fufu_Tools#83]
例如可以在这里添加对glm的支持，一键复制标签等

**Comment by Luna-Grace** [comment]
@fjwxzde set

**Comment by DuckDuckStudio** [comment]
这样做有几个问题：
1. 在填写winget清单时是否需要填写这些工具的依赖项？（如果填写，则可能产生不必要的程序安装）
2. 本工具面向普通用户，而我写的程序基本上都是终端调用。
3. 这样可能有点多余

**Comment by fjwxzde** [comment]
@Luna-Grace 
已确定管理员要求回复，在7日内未回复将自动关闭此issue

**Comment by Luna-Grace** [comment]
这确实有点难实现，我先关闭这个议题
