### ISSUE TITLE
[BUG] 自动点击在命令行失焦后暂停运行

### ISSUE THREAD

**Issue by Pfolg** [DuckDuckStudio/Fufu_Tools#84]
自动点击在命令行失焦后暂停运行
这是我写的代码，效果差不多，如果用多线程解决这个问题会比较棘手。
~~~Python
import time
import pyautogui

print("<单击>基于pyautogui实现，鼠标移至左上角停止，按Ctrl+C也可。")
delta = int(input("请输入间隔时间:"))
while True:
    pyautogui.click()
    time.sleep(delta)
~~~

**Comment by Pfolg** [comment]
问题放这我人先跑咯

**Comment by Luna-Grace** [comment]
我这里没问题啊，有更详细的复现过程或者视频吗？

**Comment by Pfolg** [comment]
上次只测试了一次，这次可以正常运行，并且主程序关闭后子程序（大概吧）还能继续运行。
不好意思，是我鲁莽了，望海涵。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DuckDuckStudio/Fufu_Tools"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月23日(星期二) 下午4:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DuckDuckStudio/Fufu_Tools] [BUG] 自动点击在命令行失焦后暂停运行 (Issue #84)





 
我这里没问题啊，有更详细的复现过程或者视频吗？

**Comment by DuckDuckStudio** [comment]
> 并且主程序关闭后子程序（大概吧）还能继续运行。

这也算是一个BUG...?（任务管理器如果有Python进程结束掉就行）

**Comment by Pfolg** [comment]
这个是优点
